import { Injectable } from '@angular/core';
import { BehaviorSubject, Subject } from 'rxjs';
import { FibonacciClient } from '../shared/autogenerated/api.generated.clients';

@Injectable({
  providedIn: 'root',
})
export class FibonacciService {
    public refreshTable$: BehaviorSubject<null> = new BehaviorSubject<null>(null);

    constructor(
        private _fibonacciClient: FibonacciClient
    ){
    }

    public getAllInfo() {
        return this._fibonacciClient.getRequestInfoHistory();
    }

    public calculateFibonacciNumber(inputNumber: number) {
        return this._fibonacciClient.calculateFibonacciNumber(inputNumber);
    }
}
